paths:
  include: ["d:/"]
  exclude: ["d:/temp/","d:/outlook/"]
es:
  address: ["http://localhost:9200","http://localhost:9201"]
  startcmd: E:\elasticsearch-7.10.0\bin\elasticsearch.bat
monitor:
  enable: true
  outpath: d:/temp/pprof/
  filescount: 30
  interval: 10
log:
  path: d:/temp/log/